### ISSUE TITLE
SecurityProtocolType

### ISSUE THREAD

**Issue by mehrdadkiani20** [deadmann/AdvancedRestHandler#46]
ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12;

     client.Timeout = new TimeSpan(0, 0, 5, 0, 0);

**Comment by deadmann** [comment]
Allow globally and locally set TLS version of the internal HttpClient

**Comment by deadmann** [comment]
@mehrdadkiani20:

 - `Timeout` has existed since version 1.0.0
 - `SslProtocols` added in version 1.6.0 and will be available shortly

Usage:

### Global:

```csharp
AdvancedRestHandler arh = new AdvancedRestHandler(string.Empty, new RestHandlerInitializerOptions
{
    SslProtocols = SslProtocols.Tls12 | SslProtocols.Tls13,
    Timeout = TimeSpan.FromSeconds(30)
});
```

-----

### Per Request:

```csharp
var res = await arh.PostDataAsync<ArhResponse<ApiRes>, ApiReq>(
    "/url-part/123", 
    new ApiReq(),
    new RestHandlerRequestOptions
    {
        SslProtocols = SslProtocols.Tls12 | SslProtocols.Tls13,
        Timeout = TimeSpan.FromSeconds(30)
    });
```
